services:
  - type: web
    name: flaskr
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT wsgi:app
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true

